name:                sonowz-raytrace
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dnsdhrj/sonowz-server
license:             BSD3
author:              SSH
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            learn
extra-source-files:
  - README.md

dependencies:
  - aeson
  - async
  - base
  - bytestring
  - containers
  - deepseq
  - directory
  - exceptions
  - filepath
  - optparse-applicative
  - process
  - relude
  - servant
  - servant-server
  - servant-websockets
  - stm
  - text
  - time
  - transformers
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector
  - warp
  - websockets

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns

executables:
  sonowz-raytrace:
    source-dirs:      src
    main:             Main.hs
