name:                sonowz-raytrace
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            learn
extra-source-files:
  - README.md

ghc-options:
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
  - -Wno-partial-type-signatures
#  - -ddump-to-file
#  - -ddump-tc-trace
#  - -fprint-potential-instances
#  - -fforce-recomp

dependencies:
  - aeson
  - async
  - base
  - bytestring
  - containers
  - deepseq
# - directory
  - exceptions
# - filepath
  - opaleye
  - optparse-applicative
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - process
  - product-profunctors
  - profunctors
  - relude
  - safe-exceptions
  - servant
  - servant-server
  - servant-websockets
  - sonowz-core
# - stm
  - text
  - time
  - transformers
  - unordered-containers
  - vector
  - warp
  - wai
  - websockets

default-extensions:
  # GHC2021 #
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances
  
  # extra #
  - ApplicativeDo           # New syntax #
  - DataKinds
  - DefaultSignatures       # New syntax #
  - DeriveAnyClass
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - RecordWildCards         # New syntax #
  - StrictData
  - TypeFamilies
  - ViewPatterns            # New syntax #


# library:
#   ghc-options:
#     - -W
#     - -Werror

executables:
  sonowz-raytrace:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      [-threaded]
