{-# LANGUAGE LambdaCase #-}

module Sonowz.Core.LLM.Gemini.Types
  ( -- * Main Request & Response
    GenerateContentRequest (..),
    mkGenerateContentRequest,
    GenerateContentResponse (..),
    responseFirstText,

    -- * Content & Parts
    Content (..),
    Part (..),
    FunctionCall (..),
    FunctionResponse (..),
    FileData (..),
    textPart,
    userContent,
    modelContent,
    systemContent,

    -- * Response Candidates & Helpers
    Candidate (..),
    candidateText,
    PromptFeedback (..),
    BlockReason (..),
    UsageMetadata (..),
    ModelStatus (..),
    ModelStage (..),
    FinishReason (..),

    -- * Tools & Configuration
    Tool (..),
    FunctionDeclaration (..),
    ToolConfig (..),
    FunctionCallingConfig (..),
    FunctionCallingMode (..),

    -- * Safety Settings & Ratings
    SafetySetting (..),
    SafetyRating (..),
    SafetyCategory (..),
    HarmBlockThreshold (..),
    HarmProbability (..),

    -- * Citation & Metadata
    CitationMetadata (..),
    CitationSource (..),
    UrlContextMetadata (..),
    UrlMetadata (..),
    UrlRetrievalStatus (..),

    -- * Service Tier
    ServiceTier (..),

    -- * Generation Configuration
    GenerationConfig (..),
    Modality (..),
    ThinkingConfig (..),
    ThinkingLevel (..),
    SpeechConfig (..),
    VoiceConfig (..),
    PrebuiltVoiceConfig (..),
    ImageConfig (..),
    MediaResolution (..),
    ResponseFormatConfig (..),
    TextResponseFormat (..),
    TextResponseMimeType (..),
    TranslationConfig (..),
  )
where

import Data.Aeson
  ( FromJSON (..),
    ToJSON (..),
    Value,
    withText,
  )
import Data.Text qualified as T
import Sonowz.Core.Imports

-- | Request body for 'models.generateContent' and 'models.streamGenerateContent'
data GenerateContentRequest = GenerateContentRequest
  { contents :: [Content],
    tools :: Maybe [Tool],
    toolConfig :: Maybe ToolConfig,
    safetySettings :: Maybe [SafetySetting],
    systemInstruction :: Maybe Content,
    generationConfig :: Maybe GenerationConfig,
    cachedContent :: Maybe Text,
    serviceTier :: Maybe ServiceTier,
    store :: Maybe Bool
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Response from the model supporting multiple candidate responses
data GenerateContentResponse = GenerateContentResponse
  { candidates :: Maybe [Candidate],
    promptFeedback :: Maybe PromptFeedback,
    usageMetadata :: Maybe UsageMetadata,
    modelVersion :: Maybe Text,
    responseId :: Maybe Text,
    modelStatus :: Maybe ModelStatus
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Structured content representing a conversation turn
data Content = Content
  { role :: Maybe Text,
    parts :: [Part]
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Individual part within a 'Content' object
data Part = Part
  { text :: Maybe Text,
    functionCall :: Maybe FunctionCall,
    functionResponse :: Maybe FunctionResponse,
    fileData :: Maybe FileData,
    thought :: Maybe Bool
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Predicted function call from model
data FunctionCall = FunctionCall
  { name :: Text,
    args :: Maybe Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Result of function execution returned to model
data FunctionResponse = FunctionResponse
  { name :: Text,
    response :: Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | URI based file data
data FileData = FileData
  { mimeType :: Maybe Text,
    fileUri :: Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Candidate response generated by model
data Candidate = Candidate
  { content :: Maybe Content,
    finishReason :: Maybe FinishReason,
    safetyRatings :: Maybe [SafetyRating],
    citationMetadata :: Maybe CitationMetadata,
    tokenCount :: Maybe Int,
    groundingAttributions :: Maybe [Value],
    groundingMetadata :: Maybe Value,
    avgLogprobs :: Maybe Double,
    logprobsResult :: Maybe Value,
    urlContextMetadata :: Maybe UrlContextMetadata,
    index :: Maybe Int,
    finishMessage :: Maybe Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Prompt feedback related to content filters
data PromptFeedback = PromptFeedback
  { blockReason :: Maybe BlockReason,
    safetyRatings :: Maybe [SafetyRating]
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Reason why prompt was blocked
data BlockReason
  = BlockReasonUnspecified
  | Safety
  | Other
  | Blocklist
  | ProhibitedContent
  | ImageSafety
  deriving (Eq, Show, Generic)

instance ToJSON BlockReason where
  toJSON = \case
    BlockReasonUnspecified -> "BLOCK_REASON_UNSPECIFIED"
    Safety -> "SAFETY"
    Other -> "OTHER"
    Blocklist -> "BLOCKLIST"
    ProhibitedContent -> "PROHIBITED_CONTENT"
    ImageSafety -> "IMAGE_SAFETY"

instance FromJSON BlockReason where
  parseJSON = withText "BlockReason" $ \case
    "BLOCK_REASON_UNSPECIFIED" -> pure BlockReasonUnspecified
    "SAFETY" -> pure Safety
    "OTHER" -> pure Other
    "BLOCKLIST" -> pure Blocklist
    "PROHIBITED_CONTENT" -> pure ProhibitedContent
    "IMAGE_SAFETY" -> pure ImageSafety
    other -> fail $ "Unknown BlockReason: " <> show other

-- | Metadata on token usage
data UsageMetadata = UsageMetadata
  { promptTokenCount :: Maybe Int,
    cachedContentTokenCount :: Maybe Int,
    candidatesTokenCount :: Maybe Int,
    toolUsePromptTokenCount :: Maybe Int,
    thoughtsTokenCount :: Maybe Int,
    totalTokenCount :: Maybe Int
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Status of the underlying model
data ModelStatus = ModelStatus
  { modelStage :: Maybe ModelStage,
    retirementTime :: Maybe Text,
    message :: Maybe Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Model stage
data ModelStage
  = ModelStageUnspecified
  | UnstableExperimental
  | Experimental
  | Preview
  | Stable
  | Legacy
  | Deprecated
  | Retired
  deriving (Eq, Show, Generic)

instance ToJSON ModelStage where
  toJSON = \case
    ModelStageUnspecified -> "MODEL_STAGE_UNSPECIFIED"
    UnstableExperimental -> "UNSTABLE_EXPERIMENTAL"
    Experimental -> "EXPERIMENTAL"
    Preview -> "PREVIEW"
    Stable -> "STABLE"
    Legacy -> "LEGACY"
    Deprecated -> "DEPRECATED"
    Retired -> "RETIRED"

instance FromJSON ModelStage where
  parseJSON = withText "ModelStage" $ \case
    "MODEL_STAGE_UNSPECIFIED" -> pure ModelStageUnspecified
    "UNSTABLE_EXPERIMENTAL" -> pure UnstableExperimental
    "EXPERIMENTAL" -> pure Experimental
    "PREVIEW" -> pure Preview
    "STABLE" -> pure Stable
    "LEGACY" -> pure Legacy
    "DEPRECATED" -> pure Deprecated
    "RETIRED" -> pure Retired
    other -> fail $ "Unknown ModelStage: " <> show other

-- | Reason token generation finished
data FinishReason
  = FinishReasonUnspecified
  | Stop
  | MaxTokens
  | FinishReasonSafety
  | Recitation
  | Language
  | FinishReasonOther
  | FinishReasonBlocklist
  | FinishReasonProhibitedContent
  | Spii
  | MalformedFunctionCall
  | FinishReasonImageSafety
  | ImageProhibitedContent
  | ImageOther
  | NoImage
  | ImageRecitation
  | UnexpectedToolCall
  | TooManyToolCalls
  | MissingThoughtSignature
  | MalformedResponse
  | Escalation
  deriving (Eq, Show, Generic)

instance ToJSON FinishReason where
  toJSON = \case
    FinishReasonUnspecified -> "FINISH_REASON_UNSPECIFIED"
    Stop -> "STOP"
    MaxTokens -> "MAX_TOKENS"
    FinishReasonSafety -> "SAFETY"
    Recitation -> "RECITATION"
    Language -> "LANGUAGE"
    FinishReasonOther -> "OTHER"
    FinishReasonBlocklist -> "BLOCKLIST"
    FinishReasonProhibitedContent -> "PROHIBITED_CONTENT"
    Spii -> "SPII"
    MalformedFunctionCall -> "MALFORMED_FUNCTION_CALL"
    FinishReasonImageSafety -> "IMAGE_SAFETY"
    ImageProhibitedContent -> "IMAGE_PROHIBITED_CONTENT"
    ImageOther -> "IMAGE_OTHER"
    NoImage -> "NO_IMAGE"
    ImageRecitation -> "IMAGE_RECITATION"
    UnexpectedToolCall -> "UNEXPECTED_TOOL_CALL"
    TooManyToolCalls -> "TOO_MANY_TOOL_CALLS"
    MissingThoughtSignature -> "MISSING_THOUGHT_SIGNATURE"
    MalformedResponse -> "MALFORMED_RESPONSE"
    Escalation -> "ESCALATION"

instance FromJSON FinishReason where
  parseJSON = withText "FinishReason" $ \case
    "FINISH_REASON_UNSPECIFIED" -> pure FinishReasonUnspecified
    "STOP" -> pure Stop
    "MAX_TOKENS" -> pure MaxTokens
    "SAFETY" -> pure FinishReasonSafety
    "RECITATION" -> pure Recitation
    "LANGUAGE" -> pure Language
    "OTHER" -> pure FinishReasonOther
    "BLOCKLIST" -> pure FinishReasonBlocklist
    "PROHIBITED_CONTENT" -> pure FinishReasonProhibitedContent
    "SPII" -> pure Spii
    "MALFORMED_FUNCTION_CALL" -> pure MalformedFunctionCall
    "IMAGE_SAFETY" -> pure FinishReasonImageSafety
    "IMAGE_PROHIBITED_CONTENT" -> pure ImageProhibitedContent
    "IMAGE_OTHER" -> pure ImageOther
    "NO_IMAGE" -> pure NoImage
    "IMAGE_RECITATION" -> pure ImageRecitation
    "UNEXPECTED_TOOL_CALL" -> pure UnexpectedToolCall
    "TOO_MANY_TOOL_CALLS" -> pure TooManyToolCalls
    "MISSING_THOUGHT_SIGNATURE" -> pure MissingThoughtSignature
    "MALFORMED_RESPONSE" -> pure MalformedResponse
    "ESCALATION" -> pure Escalation
    other -> fail $ "Unknown FinishReason: " <> show other

-- | Safety rating for content
data SafetyRating = SafetyRating
  { category :: Maybe SafetyCategory,
    probability :: Maybe HarmProbability,
    blocked :: Maybe Bool
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Harm probability
data HarmProbability
  = HarmProbabilityUnspecified
  | Negligible
  | Low
  | Medium
  | High
  deriving (Eq, Show, Generic)

instance ToJSON HarmProbability where
  toJSON = \case
    HarmProbabilityUnspecified -> "HARM_PROBABILITY_UNSPECIFIED"
    Negligible -> "NEGLIGIBLE"
    Low -> "LOW"
    Medium -> "MEDIUM"
    High -> "HIGH"

instance FromJSON HarmProbability where
  parseJSON = withText "HarmProbability" $ \case
    "HARM_PROBABILITY_UNSPECIFIED" -> pure HarmProbabilityUnspecified
    "NEGLIGIBLE" -> pure Negligible
    "LOW" -> pure Low
    "MEDIUM" -> pure Medium
    "HIGH" -> pure High
    other -> fail $ "Unknown HarmProbability: " <> show other

-- | Citation metadata
data CitationMetadata = CitationMetadata
  { citationSources :: Maybe [CitationSource]
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Citation source
data CitationSource = CitationSource
  { startIndex :: Maybe Int,
    endIndex :: Maybe Int,
    uri :: Maybe Text,
    license :: Maybe Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | URL context metadata
data UrlContextMetadata = UrlContextMetadata
  { urlMetadata :: Maybe [UrlMetadata]
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Context of single URL retrieval
data UrlMetadata = UrlMetadata
  { retrievedUrl :: Maybe Text,
    urlRetrievalStatus :: Maybe UrlRetrievalStatus
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | URL retrieval status
data UrlRetrievalStatus
  = UrlRetrievalStatusUnspecified
  | UrlRetrievalStatusSuccess
  | UrlRetrievalStatusError
  | UrlRetrievalStatusPaywall
  | UrlRetrievalStatusUnsafe
  deriving (Eq, Show, Generic)

instance ToJSON UrlRetrievalStatus where
  toJSON = \case
    UrlRetrievalStatusUnspecified -> "URL_RETRIEVAL_STATUS_UNSPECIFIED"
    UrlRetrievalStatusSuccess -> "URL_RETRIEVAL_STATUS_SUCCESS"
    UrlRetrievalStatusError -> "URL_RETRIEVAL_STATUS_ERROR"
    UrlRetrievalStatusPaywall -> "URL_RETRIEVAL_STATUS_PAYWALL"
    UrlRetrievalStatusUnsafe -> "URL_RETRIEVAL_STATUS_UNSAFE"

instance FromJSON UrlRetrievalStatus where
  parseJSON = withText "UrlRetrievalStatus" $ \case
    "URL_RETRIEVAL_STATUS_UNSPECIFIED" -> pure UrlRetrievalStatusUnspecified
    "URL_RETRIEVAL_STATUS_SUCCESS" -> pure UrlRetrievalStatusSuccess
    "URL_RETRIEVAL_STATUS_ERROR" -> pure UrlRetrievalStatusError
    "URL_RETRIEVAL_STATUS_PAYWALL" -> pure UrlRetrievalStatusPaywall
    "URL_RETRIEVAL_STATUS_UNSAFE" -> pure UrlRetrievalStatusUnsafe
    other -> fail $ "Unknown UrlRetrievalStatus: " <> show other

-- | Tool definition
data Tool = Tool
  { functionDeclarations :: Maybe [FunctionDeclaration],
    codeExecution :: Maybe Value,
    googleSearch :: Maybe Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Declaration of a function tool
data FunctionDeclaration = FunctionDeclaration
  { name :: Text,
    description :: Maybe Text,
    parameters :: Maybe Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Configuration for tools
data ToolConfig = ToolConfig
  { functionCallingConfig :: Maybe FunctionCallingConfig
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Configuration for function calling mode
data FunctionCallingConfig = FunctionCallingConfig
  { mode :: Maybe FunctionCallingMode,
    allowedFunctionNames :: Maybe [Text]
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Mode for function calling
data FunctionCallingMode
  = FunctionCallingAuto
  | FunctionCallingAny
  | FunctionCallingNone
  deriving (Eq, Show, Generic)

instance ToJSON FunctionCallingMode where
  toJSON = \case
    FunctionCallingAuto -> "AUTO"
    FunctionCallingAny -> "ANY"
    FunctionCallingNone -> "NONE"

instance FromJSON FunctionCallingMode where
  parseJSON = withText "FunctionCallingMode" $ \case
    "AUTO" -> pure FunctionCallingAuto
    "ANY" -> pure FunctionCallingAny
    "NONE" -> pure FunctionCallingNone
    other -> fail $ "Unknown FunctionCallingMode: " <> show other

-- | Safety setting threshold for blocking content
data SafetySetting = SafetySetting
  { category :: SafetyCategory,
    threshold :: HarmBlockThreshold
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Harm categories
data SafetyCategory
  = HarmCategoryUnspecified
  | HarmCategoryHateSpeech
  | HarmCategorySexuallyExplicit
  | HarmCategoryDangerousContent
  | HarmCategoryHarassment
  | HarmCategoryCivicIntegrity
  | HarmCategoryJailbreak
  deriving (Eq, Show, Generic, Enum, Bounded)

instance ToJSON SafetyCategory where
  toJSON = \case
    HarmCategoryUnspecified -> "HARM_CATEGORY_UNSPECIFIED"
    HarmCategoryHateSpeech -> "HARM_CATEGORY_HATE_SPEECH"
    HarmCategorySexuallyExplicit -> "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    HarmCategoryDangerousContent -> "HARM_CATEGORY_DANGEROUS_CONTENT"
    HarmCategoryHarassment -> "HARM_CATEGORY_HARASSMENT"
    HarmCategoryCivicIntegrity -> "HARM_CATEGORY_CIVIC_INTEGRITY"
    HarmCategoryJailbreak -> "HARM_CATEGORY_JAILBREAK"

instance FromJSON SafetyCategory where
  parseJSON = withText "SafetyCategory" $ \case
    "HARM_CATEGORY_UNSPECIFIED" -> pure HarmCategoryUnspecified
    "HARM_CATEGORY_HATE_SPEECH" -> pure HarmCategoryHateSpeech
    "HARM_CATEGORY_SEXUALLY_EXPLICIT" -> pure HarmCategorySexuallyExplicit
    "HARM_CATEGORY_DANGEROUS_CONTENT" -> pure HarmCategoryDangerousContent
    "HARM_CATEGORY_HARASSMENT" -> pure HarmCategoryHarassment
    "HARM_CATEGORY_CIVIC_INTEGRITY" -> pure HarmCategoryCivicIntegrity
    "HARM_CATEGORY_JAILBREAK" -> pure HarmCategoryJailbreak
    other -> fail $ "Unknown SafetyCategory: " <> show other

-- | Harm block thresholds
data HarmBlockThreshold
  = HarmBlockThresholdUnspecified
  | BlockLowAndAbove
  | BlockMediumAndAbove
  | BlockOnlyHigh
  | BlockNone
  | Off
  deriving (Eq, Show, Generic)

instance ToJSON HarmBlockThreshold where
  toJSON = \case
    HarmBlockThresholdUnspecified -> "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
    BlockLowAndAbove -> "BLOCK_LOW_AND_ABOVE"
    BlockMediumAndAbove -> "BLOCK_MEDIUM_AND_ABOVE"
    BlockOnlyHigh -> "BLOCK_ONLY_HIGH"
    BlockNone -> "BLOCK_NONE"
    Off -> "OFF"

instance FromJSON HarmBlockThreshold where
  parseJSON = withText "HarmBlockThreshold" $ \case
    "HARM_BLOCK_THRESHOLD_UNSPECIFIED" -> pure HarmBlockThresholdUnspecified
    "BLOCK_LOW_AND_ABOVE" -> pure BlockLowAndAbove
    "BLOCK_MEDIUM_AND_ABOVE" -> pure BlockMediumAndAbove
    "BLOCK_ONLY_HIGH" -> pure BlockOnlyHigh
    "BLOCK_NONE" -> pure BlockNone
    "OFF" -> pure Off
    other -> fail $ "Unknown HarmBlockThreshold: " <> show other

-- | Service tier options
data ServiceTier
  = ServiceTierUnspecified
  | ServiceTierPayAsYouGo
  | ServiceTierAuto
  deriving (Eq, Show, Generic)

instance ToJSON ServiceTier where
  toJSON = \case
    ServiceTierUnspecified -> "SERVICE_TIER_UNSPECIFIED"
    ServiceTierPayAsYouGo -> "SERVICE_TIER_PAY_AS_YOU_GO"
    ServiceTierAuto -> "SERVICE_TIER_AUTO"

instance FromJSON ServiceTier where
  parseJSON = withText "ServiceTier" $ \case
    "SERVICE_TIER_UNSPECIFIED" -> pure ServiceTierUnspecified
    "SERVICE_TIER_PAY_AS_YOU_GO" -> pure ServiceTierPayAsYouGo
    "SERVICE_TIER_AUTO" -> pure ServiceTierAuto
    other -> fail $ "Unknown ServiceTier: " <> show other

-- | Configuration options for model generation and outputs
data GenerationConfig = GenerationConfig
  { temperature :: Maybe Double,
    topP :: Maybe Double,
    topK :: Maybe Int,
    candidateCount :: Maybe Int,
    maxOutputTokens :: Maybe Int,
    stopSequences :: Maybe [Text],
    responseMimeType :: Maybe Text,
    responseSchema :: Maybe Value,
    responseModalities :: Maybe [Modality],
    seed :: Maybe Int,
    presencePenalty :: Maybe Double,
    frequencyPenalty :: Maybe Double,
    responseLogprobs :: Maybe Bool,
    logprobs :: Maybe Int,
    thinkingConfig :: Maybe ThinkingConfig,
    speechConfig :: Maybe SpeechConfig,
    imageConfig :: Maybe ImageConfig,
    mediaResolution :: Maybe MediaResolution,
    enableEnhancedCivicAnswers :: Maybe Bool,
    enableAffectiveDialog :: Maybe Bool,
    responseFormat :: Maybe ResponseFormatConfig,
    translationConfig :: Maybe TranslationConfig
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Response modalities
data Modality
  = ModalityUnspecified
  | ModalityText
  | ModalityImage
  | ModalityAudio
  deriving (Eq, Show, Generic)

instance ToJSON Modality where
  toJSON = \case
    ModalityUnspecified -> "MODALITY_UNSPECIFIED"
    ModalityText -> "TEXT"
    ModalityImage -> "IMAGE"
    ModalityAudio -> "AUDIO"

instance FromJSON Modality where
  parseJSON = withText "Modality" $ \case
    "MODALITY_UNSPECIFIED" -> pure ModalityUnspecified
    "TEXT" -> pure ModalityText
    "IMAGE" -> pure ModalityImage
    "AUDIO" -> pure ModalityAudio
    other -> fail $ "Unknown Modality: " <> show other

-- | Config for thinking feature
data ThinkingConfig = ThinkingConfig
  { thinkingBudget :: Maybe Int,
    thinkingLevel :: Maybe ThinkingLevel
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Thinking level options
data ThinkingLevel
  = ThinkingLevelUnspecified
  | ThinkingLevelLow
  | ThinkingLevelHigh
  deriving (Eq, Show, Generic)

instance ToJSON ThinkingLevel where
  toJSON = \case
    ThinkingLevelUnspecified -> "THINKING_LEVEL_UNSPECIFIED"
    ThinkingLevelLow -> "LOW"
    ThinkingLevelHigh -> "HIGH"

instance FromJSON ThinkingLevel where
  parseJSON = withText "ThinkingLevel" $ \case
    "THINKING_LEVEL_UNSPECIFIED" -> pure ThinkingLevelUnspecified
    "LOW" -> pure ThinkingLevelLow
    "HIGH" -> pure ThinkingLevelHigh
    other -> fail $ "Unknown ThinkingLevel: " <> show other

-- | Speech generation config
data SpeechConfig = SpeechConfig
  { voiceConfig :: Maybe VoiceConfig
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Voice config
data VoiceConfig = VoiceConfig
  { prebuiltVoiceConfig :: Maybe PrebuiltVoiceConfig
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Prebuilt voice config
data PrebuiltVoiceConfig = PrebuiltVoiceConfig
  { voiceName :: Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Config for image generation
data ImageConfig = ImageConfig
  { aspectRatio :: Maybe Text,
    imageFormat :: Maybe Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Media resolution options
data MediaResolution
  = MediaResolutionUnspecified
  | MediaResolutionLow
  | MediaResolutionMedium
  | MediaResolutionHigh
  deriving (Eq, Show, Generic)

instance ToJSON MediaResolution where
  toJSON = \case
    MediaResolutionUnspecified -> "MEDIA_RESOLUTION_UNSPECIFIED"
    MediaResolutionLow -> "MEDIA_RESOLUTION_LOW"
    MediaResolutionMedium -> "MEDIA_RESOLUTION_MEDIUM"
    MediaResolutionHigh -> "MEDIA_RESOLUTION_HIGH"

instance FromJSON MediaResolution where
  parseJSON = withText "MediaResolution" $ \case
    "MEDIA_RESOLUTION_UNSPECIFIED" -> pure MediaResolutionUnspecified
    "MEDIA_RESOLUTION_LOW" -> pure MediaResolutionLow
    "MEDIA_RESOLUTION_MEDIUM" -> pure MediaResolutionMedium
    "MEDIA_RESOLUTION_HIGH" -> pure MediaResolutionHigh
    other -> fail $ "Unknown MediaResolution: " <> show other

-- | Text response MIME type
data TextResponseMimeType
  = MimeTypeUnspecified
  | ApplicationJson
  | TextPlain
  deriving (Eq, Show, Generic, Enum, Bounded)

instance ToJSON TextResponseMimeType where
  toJSON = \case
    MimeTypeUnspecified -> "MIME_TYPE_UNSPECIFIED"
    ApplicationJson -> "APPLICATION_JSON"
    TextPlain -> "TEXT_PLAIN"

instance FromJSON TextResponseMimeType where
  parseJSON = withText "TextResponseMimeType" $ \case
    "MIME_TYPE_UNSPECIFIED" -> pure MimeTypeUnspecified
    "APPLICATION_JSON" -> pure ApplicationJson
    "TEXT_PLAIN" -> pure TextPlain
    other -> fail $ "Unknown TextResponseMimeType: " <> show other

-- | Text response format
data TextResponseFormat = TextResponseFormat
  { mimeType :: Maybe TextResponseMimeType,
    schema :: Maybe Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Configuration for response format
data ResponseFormatConfig = ResponseFormatConfig
  { text :: Maybe TextResponseFormat,
    audio :: Maybe Value,
    image :: Maybe Value
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Translation configuration
data TranslationConfig = TranslationConfig
  { targetLanguage :: Maybe Text
  }
  deriving (Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON)

-- | Helper to create a basic 'GenerateContentRequest'
mkGenerateContentRequest :: [Content] -> GenerateContentRequest
mkGenerateContentRequest contents =
  GenerateContentRequest
    { contents = contents,
      tools = Nothing,
      toolConfig = Nothing,
      safetySettings = Nothing,
      systemInstruction = Nothing,
      generationConfig = Nothing,
      cachedContent = Nothing,
      serviceTier = Nothing,
      store = Nothing
    }

-- | Helper to construct a text 'Part'
textPart :: Text -> Part
textPart txt =
  Part
    { text = Just txt,
      functionCall = Nothing,
      functionResponse = Nothing,
      fileData = Nothing,
      thought = Nothing
    }

-- | Helper to construct user 'Content'
userContent :: [Part] -> Content
userContent parts =
  Content
    { role = Just "user",
      parts = parts
    }

-- | Helper to construct model 'Content'
modelContent :: [Part] -> Content
modelContent parts =
  Content
    { role = Just "model",
      parts = parts
    }

-- | Helper to construct system 'Content'
systemContent :: Text -> Content
systemContent txt =
  Content
    { role = Nothing,
      parts = [textPart txt]
    }

-- | Extract combined text from a candidate's content parts
candidateText :: Candidate -> Maybe Text
candidateText Candidate {content = Just Content {parts = parts}} =
  let texts = mapMaybe (\Part {text = t} -> t) parts
   in if null texts then Nothing else Just (T.concat texts)
candidateText _ = Nothing

-- | Extract text from the first candidate in a response
responseFirstText :: GenerateContentResponse -> Maybe Text
responseFirstText GenerateContentResponse {candidates = Just (c : _)} = candidateText c
responseFirstText _ = Nothing
