name:                sonowz-core
version:             1.0.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            Library
extra-source-files:
  - README.md

language: GHC2021

ghc-options:
  - -O2
  - -threaded
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
  - -Wno-partial-type-signatures
#  - -fforce-recomp

dependencies:
  - ansi-terminal
  - aeson
  - async
  - base
  - bytestring
  - co-log-core
  - containers
  - cryptonite
  - deepseq
  - http-client
  - http-client-tls
  - http-types
  - opaleye
  - optparse-applicative
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - product-profunctors
  - profunctors
  - random
  - relude
  - resource-pool
  - safe-exceptions
  - servant
  - servant-server
  - text
  - time
  - unordered-containers
  - uri-bytestring
  - vector
  - wai
  - warp

default-extensions:
  - ApplicativeDo           # New syntax #
  - DataKinds
  - DefaultSignatures       # New syntax #
  - DeriveAnyClass
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - RecordWildCards         # New syntax #
  - StrictData
  - TypeFamilies
  - ViewPatterns            # New syntax #

source-dirs: src

library: {}
