name:                sonowz-core
version:             1.0.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            Library
extra-source-files:
  - README.md

ghc-options:
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
#  - -fforce-recomp

dependencies:
  - ansi-terminal
  - aeson
  - async
  - base
  - bytestring
  - co-log-core
  - containers
  - cryptonite
  - deepseq
  - http-types
  - opaleye
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - product-profunctors
  - profunctors
  - random
  - relude
  - resource-pool
  - safe-exceptions
  - servant
  - servant-server
  - text
  - time
  - unordered-containers
  - uri-bytestring
  - vector
  - wai
  - warp

default-extensions:
  - ApplicativeDo          # New syntax #
  - BangPatterns           # New syntax #
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures      # New syntax #
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - InstanceSigs
  - KindSignatures          # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NamedFieldPuns          # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - PolyKinds
  - RankNTypes
  - RecordWildCards         # New syntax #
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections           # New syntax #
  - TypeApplications        # New syntax #
  - TypeFamilies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns            # New syntax #


library:
  source-dirs:      src
