name:                sonowz-core
version:             1.0.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            Library
extra-source-files:
  - README.md

ghc-options:
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
  - -Wno-partial-type-signatures
#  - -fforce-recomp

dependencies:
  - ansi-terminal
  - aeson
  - async
  - base
  - bytestring
  - co-log-core
  - containers
  - cryptonite
  - deepseq
  - http-client
  - http-client-tls
  - http-types
  - opaleye
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - product-profunctors
  - profunctors
  - random
  - relude
  - resource-pool
  - safe-exceptions
  - servant
  - servant-server
  - text
  - time
  - unordered-containers
  - uri-bytestring
  - vector
  - wai
  - warp

default-extensions:
  # GHC2021 #
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances
  
  # extra #
  - ApplicativeDo           # New syntax #
  - DataKinds
  - DefaultSignatures       # New syntax #
  - DeriveAnyClass
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - RecordWildCards         # New syntax #
  - StrictData
  - TypeFamilies
  - ViewPatterns            # New syntax #


library:
  source-dirs:      src
