name:                sonowz-mp3tag-autofix
version:             1.0.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            audio
extra-source-files:
  - README.md

language: GHC2021

ghc-options:
  - -O2
  - -threaded
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
  - -Wno-partial-type-signatures
#  - -fforce-recomp

dependencies:
  - ansi-terminal
  - aeson
  - async
  - base
  - bytestring
  - containers
  - co-log-core
  - deepseq
  - directory
  - filepath
  - htaglib
  - optparse-applicative
  - polysemy
  - polysemy-plugin
  - pretty-simple
  - random
  - relude
  - sonowz-core
  - tagsoup
  - text
  - text-icu
  - time
  - uri-bytestring
  - vector

default-extensions:
  - ApplicativeDo           # New syntax #
  - DataKinds
  - DefaultSignatures       # New syntax #
  - DeriveAnyClass
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - RecordWildCards         # New syntax #
  - StrictData
  - TypeFamilies
  - ViewPatterns            # New syntax #

source-dirs: src

executables:
  sonowz-mp3tag-autofix:
    main:             Main.hs
