name:                sonowz-noti
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/sonowz/sonowz-backend
license:             BSD3
author:              SoonHo Seo
maintainer:          dnsdhrj123@gmail.com
copyright:           MIT
category:            Application
extra-source-files:
  - README.md

language: GHC2021

ghc-options:
  - -O2
  - -threaded
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -W
  - -Wno-partial-type-signatures
#  - -fforce-recomp

dependencies:
  - base
  - bytestring
  - containers
  - mime-mail
  - opaleye
  - optparse-applicative
  - product-profunctors
  - profunctors
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - relude
  - resource-pool
  - safe-exceptions
  - smtp-mail
  - sonowz-core
  - text
  - time
  - vector

default-extensions:
  - ApplicativeDo           # New syntax #
  - DataKinds
  - DefaultSignatures       # New syntax #
  - DeriveAnyClass
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies  # New syntax #
  - GADTs                   # New syntax #
  - LambdaCase              # New syntax #
  - MonadComprehensions     # New syntax #
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp        # New syntax #
  - PartialTypeSignatures   # New syntax #
  - RecordWildCards         # New syntax #
  - StrictData
  - TypeFamilies
  - ViewPatterns            # New syntax #

source-dirs: src

library:
  when:
  - condition: false
    exposed-modules:
      - Main

executables:
  sonowz-noti:
    main:             Main.hs
